### ISSUE TITLE
命令行也安装不成功，sharp相关依赖解决不了

### ISSUE THREAD

**Issue by appotry** [hans362/picgo-plugin-remove-exif#7]
win x64平台，依赖解决不了
sharp-libvips
```
npm ERR! path C:\Users\xxxx\AppData\Roaming\picgo\node_modules\picgo-plugin-remove-exif\node_modules\sharp
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile &
& node-gyp rebuild && node install/dll-copy)
npm ERR! sharp: Downloading https://npm.taobao.org/mirrors/sharp-libvips/libvips-8.12.2-win32-x64.tar.br
npm ERR! sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies
npm ERR! sharp: Installation error: Prebuilt libvips 8.12.2 binaries are not yet available for win32-x64
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxxx\AppData\Local\npm-cache\_logs\2022-09-14T04_40_02_486Z-debug.log
```

**Comment by hans362** [comment]
参考 https://sharp.pixelplumbing.com/install#chinese-mirror 尝试切换一下镜像源
```
npm config set sharp_binary_host "https://npmmirror.com/mirrors/sharp"
npm config set sharp_libvips_binary_host "https://npmmirror.com/mirrors/sharp-libvips"
```

**Comment by appotry** [comment]
sharp-libvips 安装失败， sharp 这个镜像能够解决

```
npm ERR! sharp: Downloading
https://npmmirror.com/mirrors/sharp-libvips/libvips-8.12.2-win32-x64.tar.br
npm ERR! sharp: Please see https://sharp.pixelplumbing.com/install for
required dependencies
npm ERR! sharp: Installation error: Prebuilt libvips 8.12.2 binaries are
not yet available for win32-x64
```

https://sharp.pixelplumbing.com/install#prebuilt-libvips-binaries
这个文档说sharp-libvips需要从源码编译安装，写的也不够详细，有没有个sharp-libvips 详细安装教程

或者把这个插件编译打包进入picgo-plugin-remove-exif ？

Hans362 ***@***.***> 于2022年9月14日周三 13:06写道：

**Comment by hans362** [comment]
prebuilt 意思是预编译的，文档没问题，不需要从源码编译安装
感觉还是国内镜像有问题，https://npmmirror.com/mirrors/sharp-libvips/libvips-8.12.2-win32-x64.tar.br 这个链接不知道为啥打开直接404，可能得试试撤掉镜像通过某些不能说的上网手段安装
我自己这通过某些不能说的上网手段安装成功

**Comment by appotry** [comment]
阿里镜像坑死人，换了个镜像，安装成功了

```
npm config set registry https://mirrors.huaweicloud.com/repository/npm/
```

**Comment by appotry** [comment]
阿里镜像坑死人，换了个镜像，安装成功了

```
npm config set registry https://mirrors.huaweicloud.com/repository/npm/
```

**Comment by appotry** [comment]
以前安装picgo-plugin-compress插件时，记得遇到同样问题

后来picgo-plugin-compress插件是把依赖包含了还是怎么解决的，解决方法似乎可以参考这个插件

AndyOnLine ***@***.***> 于2022年9月14日周三 13:57写道：

**Comment by liuliangsir** [comment]
> prebuilt 意思是预编译的，文档没问题，不需要从源码编译安装 感觉还是国内镜像有问题，https://npmmirror.com/mirrors/sharp-libvips/libvips-8.12.2-win32-x64.tar.br 这个链接不知道为啥打开直接404，可能得试试撤掉镜像通过某些不能说的上网手段安装 我自己这通过某些不能说的上网手段安装成功

好像这样访问才行，https://npmmirror.com/mirrors/sharp-libvips/v8.12.2/libvips-8.12.2-win32-x64.tar.br
